spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/fooddelivery?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  
  data:
    redis:
      host: ${REDIS_HOST:192.168.48.128}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:127.0.0.1:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:food-delivery-seckill}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.food.delivery.dto.messaging
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.food.delivery.dto.messaging.SeckillClaimEvent
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.food.delivery.entity

logging:
  level:
    '[com.food.delivery]': info

app:
  seckill:
    redis-lua-enabled: true
    kafka-enabled: true
  delivery:
    enabled: ${DELIVERY_ENABLED:true}
    realtime-enabled: ${DELIVERY_REALTIME_ENABLED:true}
    location-store-enabled: ${DELIVERY_LOCATION_STORE_ENABLED:true}
    location-min-interval-ms: ${DELIVERY_LOCATION_MIN_INTERVAL_MS:1000}

